- hosts: all
  tasks:
   - name: Install Apache websever
      package:
         name: "docker pull aniket86/webserver:${BUILD_TAG}"
         state: present
         
   - name: Start Apache Web Service
      command: /usr/sbin/httpd
      changed_when: false

