- hosts: all
  tasks:
   - name: installing web server
     package:
       name: "docker"
       state: present

   - name: startig the web server
     service:
             name: "docker"
             state: started
             enabled: yes
             
   - name: ensure a container is running
     docker_container:
       name: webapp
       state: started
       image: "docker pull aniket86/webserver:jenkins-project-28"
       pull: true
       ports:
         - "5000:5000"
   

