- hosts: all
  tasks:
   - name: installing web server
     package:
       name: "docker"
       state: present

   - name: startig the web server
     service:
             name: "docker"
             state: started
             enabled: yes
   

