- hosts: all
  tasks:
   - name: setting up requirments for docker 
     command: "pip3 install docker"
     command: "pip3 install docker-py>=1.7.0"
     command: "pip3 install docker-compose>=1.7.0"
     
   - name: installing docker
     package:
       name: "docker"
       state: present

   - name: startig docker services
     service:
             name: "docker"
             state: started
             enabled: yes
             
   - name: ensure a container is running
     docker_container:
       name: webapp
       state: started
       image: "aniket86/webserver:jenkins-project-32"
       pull: true
       ports:
         - "5000:80"
   

