- hosts: all
  tasks:
   - name: installing web server
     package:
       name: "docker"
       state: present

   - name: startig the web server
     service:
             name: "docker"
             state: started
             enabled: yes
             
    
   - name: Stop a container
     docker_container:
       name: webapp
       state: stopped
             
   - name: ensure a container is running
     docker_container:
       name: webapp
       state: started
       image: "aniket86/webserver:jenkins-project-32"
       pull: true
       ports:
         - "5000:80"
   

